# _config.yml

title: "Roleplaying Adventures"
description: "A blog about ESO Roleplaying Adventures"
baseurl: "" # Leave this blank if deploying to GitHub Pages on user/organization site
url: "https://github.com/unvailedsmoke/eso.rp.blog.github.io.git" # Change this to your GitHub Pages URL
author: "Your Name"
markdown: kramdown
theme: minima

# Build settings
paginate: 5
