title: My ESO Blog
description: "A blog about ESO Roleplaying Adventures."
author: Your Name
baseurl: "" # Base URL for the site, leave empty for root
url: "http://your-github-username.github.io/your-repo-name" # Your GitHub Pages URL

# Build settings
markdown: kramdown
theme: minima # You can choose a theme or use the default
permalink: pretty

# Plugins
plugins:
  - jekyll-feed

# Social links (if applicable)
social:
  twitter: "https://twitter.com/yourhandle"
  github: "https://github.com/yourhandle"
  linkedin: "https://linkedin.com/in/yourhandle"

# Include directories
include:
  - _pages
  - assets

# Exclude files or directories
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - _config.yml
  - node_modules
  - vendor
